config/routes.rb
Rails.application.routes.draw do
  get 'snaps/new'

  resources :users do
    resources :albums, shallow: true do
      resources :snaps, shallow: true
    end
  end

  resources :sessions, only: [:create, :destroy]

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup',  to: 'users#new', as: 'signup'

  root 'static#home'

  # root 'welcome#index'

  # Example resource route (maps HTTP verbs to controller actions
  # automatically):
  #   resources :products

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end
end

app/models/album.rb
# models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :snaps
  accepts_nested_attributes_for :snaps

  validates :name,
            presence: true,
            uniqueness: { case_sensitive: false, scope: :user_id }

  validates_presence_of :user_id
  validate :user_exists

  private

  def user_exists
    errors.add(:user_id, 'doesn\'t exist') unless
    User.exists?(user_id)
  end
end

app/models/snap.rb
# app/models/snap.rb
class Snap < ActiveRecord::Base
  belongs_to :album
  delegate :user, to: :album

  # dragonfly
  extend Dragonfly::Model
  dragonfly_accessor :image

  validates_size_of(:image,
                    maximum: 3.megabytes,
                    message: 'should be no more than 3 megabytes')

  validates_property(:format,
                     of: :image,
                     in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false,
                     message: 'should be either .jpeg, .jpg, .png, .bmp')
end

app/models/user.rb
#
class User < ActiveRecord::Base
  class Unauthorized < StandardError; end
  has_secure_password

  has_many :albums, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :albums

  # paginate
  self.per_page = 10

  # form
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: true },
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }

  # Dragonfly Images
  extend Dragonfly::Model
  dragonfly_accessor :avatar
  # validates_presence_of :avatar

  validates_size_of(:avatar,
                    maximum: 3.megabytes,
                    message: 'should be no more than 3 megabytes')

  validates_property(:format,
                     of: :avatar,
                     in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false,
                     message: 'should be either .jpeg, .jpg, .png, .bmp')
end

app/controllers/albums_controller.rb
# # controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :check_user, only: [:edit, :update]

  def index
    @albums = Album.paginate(page: params[:page])
  end

  def new
    @album = user.albums.new
  end

  def create
    current_user?
    @album = user.albums.new(album_params)
    if album.save
      redirect_to user
      flash[:notice] = 'Album creation success'
    else
      render 'new'
    end
  end

  def edit
    user
  end

  def update
    if album.update_attributes(album_params)
      redirect_to current_user, notice: 'Album update success'
    else
      render :edit
    end
  end

  def show
    album
  end

  private

  def album_params
    params.require(:album).permit(:name, :user_id, :snap_id)
  end

  def album
    @album ||= Album.find(params[:id])
  end

  # refactored
  def user
    return album.user unless params[:user_id].present?
    @_album ||= User.find(params[:user_id])
  end

  def current_user?
    if current_user.id == params[:user_id]
      current_user
    else
      User.find(params[:user_id])
    end
  end

  def logged_in?
    return false unless current_user
    params[:id] == current_user.id.to_s
  end

  def check_user
    if logged_in?
      current_user
    else
      redirect_to root_url, notice: 'unauthorized'
    end
  end
end

app/controllers/application_controller.rb
# controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  private

  def current_user
    @_current_user ||=
    session[:current_user_id] &&
    User.find_by(id: session[:current_user_id])
  end

  helper_method :current_user, :logged_in?
end

app/controllers/sessions_controller.rb
# contollers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # if user exists with entered password is correct
    if user.authenticate(params[:password])
      # save the user id
      session[:current_user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now[:alert] = 'Email or password is invalid'
      render 'new'
    end
  end

  def destroy
    session[:current_user_id] = nil
    flash[:notice] = 'You have successfully logged out.'
    redirect_to root_url
  end

  private

  def user
    @_user ||= User.find_by_email(params[:email]) || null_user
  end

  def null_user
    Struct.new('User') do
      def authenticate(_)
        false
      end
    end.new
  end
end

app/controllers/snaps_controller.rb
# app/controller/snaps_controller.rb
class SnapsController < ApplicationController
  before_action :check_user, except: [:show, :index]

  def index
    @snaps = Snap.paginate(page: params[:page])
  end

  def new
    @snap = current_user.snap.new
  end

  def create
    @snap = current_user.snaps.new(snap_params)
    if @snap.save
      redirect_to @current_user
      flash[:notice] = 'Snap creation success'
    else
      render 'new'
    end
  end

  def edit
    @snap = Snap
  end

  def update
    @snap = snap
    if @snap.update_attributes(snap_params)
      redirect_to current_user, notice: 'Snap update success'
    else
      render :edit
    end
  end

  def show
    @snap = Snap.find(params[:id])
  end

  private

  def snap_params
    params.require(:snap).permit(
      :name,
      :image_uid,
      :image_name,
      :year,
      :color,
      :description,
      :album_id
    )
  end

  def snap
    @snap ||= Snap.find(params[:id])
  end
end

app/controllers/static_controller.rb
#
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
# controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to root_path
      flash[:notice] = 'Thanks for signing up.'
    else
      flash[:notice] = 'There was an issue signing up, please try again.'
      render 'new'

    end
  end

  def edit
    user
  end

  def update
    if user.update_attributes(user_params)
      redirect_to user_path(user), notice: 'success'
    else
      render :edit
    end
  end

  def show
    user
  end

  private

  def user
    @user = User.find(params[:id])
  end

  def logged_in?
    return false unless current_user
    params[:id] == current_user.id.to_s
  end

  def check_user
    if logged_in?
      @current_user
    else
      redirect_to root_url, notice: 'unauthorized'
    end
  end

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
#
module ApplicationHelper
end

app/helpers/session_helper.rb
#
module SessionHelper
  def avatar(user)
    return image_tag user.avatar.thumb('200x100#').url if user.avatar_stored?
  end

  def signup_link
    return link_to_unless_current 'Sign Up', signup_path unless current_user
    ''
  end

  def login_link
    return link_to 'Login', login_path unless current_user
    ''
  end

  def logout_link
    return link_to 'Logout', logout_path if current_user
    ''
  end

  def user_link
    return link_to 'Account', user_path(current_user) if current_user
    ''
  end
  # def edit_link
  #   return link_to 'edit'
  #   edit_user_path(current_user) if user_path(current_user)
  #   ''
  # end
end

app/helpers/snaps_helper.rb
# app/helpers/snaps_helper.rb
module SnapsHelper
end

app/views/albums/edit.html.haml
%h1 Edit Album
#edit-album
  = form_for @album do |f|
    - if @album.errors.any?
      .error-messages
        %h2 Form is invalid
        %ul
          - @album.errors.full_messages.each do |message|
            %li= message

    .field
      = f.label :name
      = f.text_field :name

    .field
      = f.label :image, 'Change image'
      = f.file_field :image




    .actions
      = f.submit 'submit'

app/views/albums/index.html.haml
%h1  All Albums
%p= will_paginate @albums
%ul
  - @albums.each do |album|
    %li= link_to album_path, user

app/views/albums/new.html.haml
%h1 Create Album
#new-album
  = form_for ([@album.user, @album]) do |f|
    - if @album.errors.any?
      .error-messages
        %h2 Form is invalid
        %ul
          - @album.errors.full_messages.each do |message|
            %li= message

    .field
      = f.label :name
      = f.text_field :name

    .field
      = f.label :image, 'add image'
      = f.file_field :image

    .actions
      = f.submit 'submit'

app/views/albums/show.html.haml
%h2 Users Albums
%ul
  - @user.albums.each do |album|
    %li= link_to album.name, edit_album_path(album)
%ul
  - if logged_in?
    %li= link_to 'Add album', new_user_album_path(current_user)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Collections
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    #container
      #user-header
        = signup_link
        = login_link
        = user_link
        = logout_link


      - flash.each do |name, msg|
        = content_tag :div, msg, class: name

    = yield

app/views/snaps/edit.html.haml
%h1 Edit Images
#edit-album
  = form_for @album do |f|
    - if @album.errors.any?
      .error-messages
        %h2 Form is invalid
        %ul
          - @album.errors.full_messages.each do |message|
            %li= message

    .field
      = f.label :name
      = f.text_field :name

    .field
      = f.label :image, 'Change image'
      = f.file_field :image




    .actions
      = f.submit 'submit'

app/views/snaps/index.html.haml
%h1  All Snaps
%p= will_paginate @snaps
%ul
  - @snaps.each do |snap|
    %li= link_to snap_path, album

app/views/snaps/new.html.haml
%h1 Add Snaps
#new-snaps
  = form_for ([@snap.album, @album]) do |f|
    - if @snap.errors.any?
      .error-messages
        %h2 Form is invalid
        %ul
          - @snap.errors.full_messages.each do |message|
            %li= message

    .field
      = f.label :name
      = f.text_field :name

    .field
      = f.label :image, 'add image'
      = f.file_field :image

    .field
      = f.label :year, 'Add year of image'
      = f.select :year, (Time.zone.now.year - 50)..(Time.zone.now.year)

    .field
      = f.label :color, 'Primary image color'
      = f.text_field :color

    .field
      = f.label :description 'Image description'
      = f.text_field :description

    .actions
      = f.submit 'submit'

app/views/snaps/show.html.haml
%h2 Users Image
%ul
  - @snap.albums.each do |snap|
    %li= link_to snap.name, edit_snap_path(album)
%ul
  - if current_user.present?
    %li= link_to 'Add snap', new_album_snap(current_user)

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    .error-messages
      %h2 Form is invalid
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :email
    = f.text_field :email

  .field
    = f.label :password
    = f.password_field :password

  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation

  .actions
    = f.submit 'submit'

app/views/users/edit.html.haml
%h2 Edit User
%p User:  #{@user.email}
#edit-user
  = form_for(@user) do |f|
    - if @user.errors.any?
      .error-messages
        %h2 Form is invalid
        %ul
          - @user.errors.full_messages.each do |message|
            %li= message

    .field
      %p= f.label :email, 'Email:'
      %p= f.text_field :email

    .field
      %p= f.label :avatar, 'Change Avatar:'
      %p= f.file_field :avatar

    .actions
      %p= f.submit 'submit'

app/views/users/index.html.haml
%h1  All Users
%p= will_paginate @users
%ul
  - @users.each do |user|
    %li= link_to user.email, user

app/views/users/new.html.haml
%h1 Sign Up
#new-user
  = form_for(@user) do |f|
    - if @user.errors.any?
      .error-messages
        %h2 Form is invalid
        %ul
          - @user.errors.full_messages.each do |message|
            %li= message

    .field
      %p= f.label :email, 'Email:'
      %p= f.text_field :email

    .field
      %p= f.label :password, 'Password:'
      %p= f.password_field :password

    .field
      %p= f.label :password_confirmation, 'Password Confirmation:'
      %p= f.password_field :password_confirmation

    .field
      %p= f.label :avatar, 'Add avatar:'
      %p= f.file_field :avatar

    .actions
      %h1= f.submit 'Sign Up'

app/views/users/show.html.haml
#user
  %h2 User Profile

  %ul
    %li Email:
    %li= "user id: #{@user.id}"
    %li= link_to @user.email, edit_user_path(@user)

  %ul
    %li Avatar:
    %li= link_to avatar(@user), edit_user_path(@user)


  %h2 Users Albums

  %ul
    - @user.albums.each do |album|
      %li= link_to album.name, edit_album_path(album)
  %ul
    - if current_user.present?
      %li= link_to 'Add album', new_user_album_path(@user)